#!/bin/bash -e

LIB=/usr/local/lib
SHARE=/usr/local/share
SRC=/usr/local/src

cd $SRC


# unpack electrum
tar -zxf Electrum-*.tar.gz
rm Electrum-*.tar.gz

# install electrum
mv Electrum-*/ $SHARE/electrum/
sudo ln -s $SHARE/electrum/electrum /usr/local/bin/electrum
sudo chmod +x /usr/local/bin/electrum

# unpack Exodus
unzip exodus-*.zip -d .
rm exodus-*.zip

# install Exodus
mv Exodus*/ $LIB/exodus/
sudo ln -s $LIB/exodus/Exodus /usr/local/bin/exodus
sudo chmod +x /usr/local/bin/exodus

# unpack CryptoSeed
unzip CryptoSeed*.zip
rm CryptoSeed*.zip

# install CryptoSeed
mv CryptoSeed*/ $LIB/cryptoseed/
sudo ln -s $LIB/cryptoseed/cryptoseed /usr/local/bin/cryptoseed
sudo chmod +x /usr/local/bin/cryptoseed

# install keepassxc
sudo dpkg -i keepassxc*.deb
rm keepassxc*.deb

# install armory
sudo dpkg -i armory*.deb
rm armory*.deb
